import json
from dataclasses import dataclass
from typing import Generic, TypeVar

from typing import Generic, TypeVar

# AsyncAnthropic is Anthropic's asynchronous Python SDK client.
# We use it to send requests to the Claude API without blocking the FastAPI application while waiting for a response.
from anthropic import AsyncAnthropic

from pydantic import BaseModel, ValidationError

# get_settings() gives us application configuration
from app.config import get_settings

from pydantic import BaseModel, ValidationError


# Custom exception for Claude-related configuration problems.
# This lets us distinguish configuration errors from other runtime errors.
class ClaudeConfigurationError(RuntimeError):
    pass

class ClaudeResponseError(RuntimeError):
    pass


ModelT = TypeVar("ModelT", bound=BaseModel)



# This class defines the result that OUR application wants to receive back from ClaudeService.
# frozen=True makes the object immutable after it is created.
@dataclass(frozen=True)
class ClaudeTextResult:
    text: str # The text generated by Claude.
    model: str # The Claude model that produced the response.
    input_tokens: int # Number of tokens Claude processed as input.
    output_tokens: int # Number of tokens Claude generated as output.


StructuredModel = TypeVar(
    "StructuredModel",
    bound=BaseModel,
)

@dataclass(frozen=True)
class ClaudeStructuredResult(
    Generic[StructuredModel]
):
    data: StructuredModel
    model: str
    input_tokens: int
    output_tokens: int


@dataclass(frozen=True)
class ClaudeStructuredResult(Generic[ModelT]):
    data: ModelT
    model: str
    input_tokens: int
    output_tokens: int


class ClaudeService:
    def __init__(self) -> None:
        self.settings = get_settings()
        if self.settings.anthropic_api_key is None:
            raise ClaudeConfigurationError("Claude API key is not configured.")
        if self.settings.claude_model is None:
            raise ClaudeConfigurationError("Claude model is not configured.")
        self.model = self.settings.claude_model
        self.client = AsyncAnthropic(
            api_key=self.settings.anthropic_api_key.get_secret_value().strip(),
            timeout=self.settings.claude_timeout_seconds,
            max_retries=self.settings.claude_max_retries,
        )

    async def generate_text(
        self,
        user_message: str, # The actual message/task that we want Claude to process.

        # The * means the remaining arguments must be supplied by name.
        # Example: generate_text("Hello", max_tokens=100)
        # This makes function calls easier to understand.
        *,
        max_tokens: int = 300,

        # Optional system/application instruction. Example: "You are a customer-support summariser."
        # str | None means it may contain a string or None.
        system: str | None = None,

    ) -> ClaudeTextResult:

        # Build the request that will be sent to Claude. This is just a normal Python dictionary.
        request = {
            "model": self.model, # Which Claude model should process the request?
            "max_tokens": max_tokens, # Maximum number of output tokens Claude is allowed to generate.
            "messages": [
                {
                    "role": "user", # This message came from the user/application.
                    "content": user_message, # The actual text Claude should process.
                }
            ],
        }

        # Only include the system instruction if one was supplied.
        # If system is None or empty, this block is skipped.
        if system:
            request["system"] = system

        # ---------------------------------------------------------
        # THIS PART IS THE ACTUAL CLAUDE API CALL
        # for more info, see the Anthropic SDK docs: https://platform.claude.com/docs/en/api/python/messages/create
        # ---------------------------------------------------------
        #   self.client = our AsyncAnthropic SDK client
        #   .messages = the Messages API section of the SDK
        #   .create(...) = create/send a new Claude message request
        #   await = wait asynchronously for Anthropic to respond
        #
        # The object returned by Anthropic is stored in "message".
        #   request["messages"] is what we SEND to Claude.
        #   message is the response object we RECEIVE from Claude.
        message = await self.client.messages.create(
            **request   # **request = unpack the Python dictionary into named arguments
        )

        # This list comprehension, used to extract text parts from Claude's response:
        # [
        #     block.text
        #     for block in message.content
        #     if block.type == "text"
        # ]
        #
        # is equivalent to:
        #
        # text_parts = []
        # for block in message.content:
        #     if block.type == "text":
        #         text_parts.append(block.text)
        #
        # Why use a list comprehension instead of a for loop?
        # It is not required, but it works nicely here because the Claude SDK
        # gives us a collection of content block objects with predictable attributes
        # such as block.type and block.text.

        text_parts = [
            block.text
            for block in message.content # message.content contains Claude's response content blocks.
            if block.type == "text" # A response may contain different kinds of content blocks, so we only collect blocks whose type is "text".
        ]

        text = "\n".join(text_parts).strip() # Join all text blocks together using a newline.

        # Converts Anthropic's SDK response into our app's (simpler) ClaudeTextResult object.
        # This means routes and other services do not need to know the internal structure of the Anthropic response.
        return ClaudeTextResult(
            text=text, # Claude's generated text.
            model=message.model, # The model reported by Anthropic in the response.
            input_tokens=message.usage.input_tokens, # How many tokens Claude processed as input.
            output_tokens=message.usage.output_tokens, # How many tokens Claude generated as output.
        )

    async def generate_structured(
        self,
        user_message: str,
        *,
        output_model: type[StructuredModel],
        max_tokens: int = 500,
        system: str | None = None,
    ) -> ClaudeStructuredResult[StructuredModel]:
        request = {
            "model": self.settings.claude_model,
            "max_tokens": max_tokens,
            "messages": [
                {
                    "role": "user",
                    "content": user_message,
                }
            ],
            "output_format": output_model,
        }

        if system:
            request["system"] = system

        message = await self.client.messages.create(**request)

        text_parts = [block.text for block in message.content if block.type == "text"]

        return ClaudeStructuredResult(
            data=message.parsed_output,
            model=message.model,
            input_tokens=message.usage.input_tokens,
            output_tokens=message.usage.output_tokens,
        )

    async def generate_structured(
        self,
        user_message: str,
        *,
        schema: type[ModelT],
        max_tokens: int = 600,
        system: str | None = None,
    ) -> ClaudeStructuredResult[ModelT]:
        result = await self.generate_text(
            user_message=user_message,
            max_tokens=max_tokens,
            system=system,
        )

        payload = _extract_json_object(result.text)

        try:
            data = schema.model_validate(payload)
        except ValidationError as e:
            raise ClaudeResponseError(
                f"Claude returned JSON that does not match {schema.__name__}: {e}"
            ) from e

        return ClaudeStructuredResult(
            data=data,
            model=result.model,
            input_tokens=result.input_tokens,
            output_tokens=result.output_tokens,
        )

    async def close(self) -> None:
        await self.client.close()


def _extract_json_object(text: str) -> dict:
    """Parse the first JSON object in a Claude reply, tolerating code fences."""
    candidate = text.strip()

    if candidate.startswith("```"):
        candidate = candidate.split("```")[1]
        if candidate.lstrip().lower().startswith("json"):
            candidate = candidate.lstrip()[4:]
        candidate = candidate.strip()

    start = candidate.find("{")
    end = candidate.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ClaudeResponseError("Claude did not return a JSON object.")

    try:
        payload = json.loads(candidate[start : end + 1])
    except json.JSONDecodeError as e:
        raise ClaudeResponseError(f"Claude returned invalid JSON: {e}") from e

    if not isinstance(payload, dict):
        raise ClaudeResponseError("Claude returned JSON that is not an object.")

    return payload
