# route/service -> ClaudeService -> Anthropic SDK
# input -> build one Claude request -> send request -> receive response -> return result
# Goal -> decide what to do -> choose tool
'''
generate_text() ->  normal text      send a message to Claude and get back text
generate_structured() -> validated structured data (Pydantic model)      send a message to Claude and get back structured data
generate_with_tools() -> final text after running any tools Claude asked for
generate_text_stream() -> text yielded piece by piece while Claude is still writing
create_message() -> raw content send a message to Claude and get back a message object (for tool use)
'''

import asyncio
import json
from collections.abc import AsyncIterator, Awaitable, Callable, Mapping

# A dataclass is a simple way to create a class whose main purpose is to hold data.
from dataclasses import dataclass

from typing import Generic, TypeVar, Any

# AsyncAnthropic is Anthropic's asynchronous Python SDK client.
# We use it to send requests to the Claude API without blocking the FastAPI application while waiting for a response.
from anthropic import AsyncAnthropic

from pydantic import BaseModel, ValidationError

# get_settings() gives us application configuration
from app.config import get_settings


# Custom exception for Claude-related configuration problems.
# This lets us distinguish configuration errors from other runtime errors.
class ClaudeConfigurationError(RuntimeError):
    pass

class ClaudeResponseError(RuntimeError):
    pass


ModelT = TypeVar("ModelT", bound=BaseModel)



# One tool call Claude asked us to run.
# Claude never runs a tool itself: it only says "please call tool X with these arguments",
# and OUR application decides whether and how to execute it.
@dataclass(frozen=True)
class ClaudeToolCall:
    id: str         # Anthropic's id for this call; the result must be sent back with the same id.
    name: str       # Which tool Claude wants (matches the "name" in the tool definition).
    arguments: dict # The arguments Claude filled in, already parsed into a Python dict.


# A tool handler is an async function that takes the arguments dict and returns a string result.
# Example: async def lookup_order(args: dict) -> str: ...
ToolHandler = Callable[[dict], Awaitable[str]]


# This class defines the result that OUR application wants to receive back from ClaudeService.
# frozen=True makes the object immutable after it is created.
@dataclass(frozen=True)
class ClaudeTextResult:
    text: str # The text generated by Claude.
    model: str # The Claude model that produced the response.
    input_tokens: int # Number of tokens Claude processed as input.
    output_tokens: int # Number of tokens Claude generated as output.

    # Why Claude stopped: "end_turn", "tool_use", "max_tokens", ...
    # "tool_use" means Claude is waiting for us to run the tools listed below.
    stop_reason: str | None = None

    # Tool calls Claude requested. Empty when no tools were offered or none were used.
    # A tuple (not a list) because this dataclass is frozen/immutable.
    tool_calls: tuple[ClaudeToolCall, ...] = ()


@dataclass(frozen=True)
class ClaudeStructuredResult(Generic[ModelT]):
    data: ModelT
    model: str
    input_tokens: int
    output_tokens: int


class ClaudeService:
    def __init__(self) -> None:
        self.settings = get_settings()
        if self.settings.anthropic_api_key is None:
            raise ClaudeConfigurationError("Claude API key is not configured.")
        if self.settings.claude_model is None:
            raise ClaudeConfigurationError("Claude model is not configured.")
        self.model = self.settings.claude_model
        self.client = AsyncAnthropic(
            api_key=self.settings.anthropic_api_key.get_secret_value().strip(),
            timeout=self.settings.claude_timeout_seconds,
            max_retries=self.settings.claude_max_retries,
        )

    async def generate_text(
        self,
        user_message: str, # The actual message/task that we want Claude to process.

        # The * means the remaining arguments must be supplied by name.
        # Example: generate_text("Hello", max_tokens=100)
        # This makes function calls easier to understand.
        *,
        max_tokens: int = 300,

        # Optional system/application instruction. Example: "You are a customer-support summariser."
        # str | None means it may contain a string or None.
        system: str | None = None,

        # Optional tool definitions Claude is allowed to ask for.
        # This is a LIST of tool schemas, e.g.
        # [{"name": "lookup_order", "description": "...", "input_schema": {...}}]
        # Offering a tool does not run anything: see generate_with_tools() for that.
        tools: list[dict] | None = None,

    ) -> ClaudeTextResult:

        # Build the request that will be sent to Claude. This is just a normal Python dictionary.
        request = {
            "model": self.model, # Which Claude model should process the request?
            "max_tokens": max_tokens, # Maximum number of output tokens Claude is allowed to generate.
            "messages": [
                {
                    "role": "user", # This message came from the user/application.
                    "content": user_message, # The actual text Claude should process.
                }
            ],
        }

        # Only include the system instruction if one was supplied.
        # If system is None or empty, this block is skipped.
        if system:
            request["system"] = system

        # Only send the "tools" field when we actually have tools to offer.
        # Note the plural: the Messages API parameter is "tools", and it expects a list.
        if tools:
            request["tools"] = tools

        # ---------------------------------------------------------
        # THIS PART IS THE ACTUAL CLAUDE API CALL
        # for more info, see the Anthropic SDK docs: https://platform.claude.com/docs/en/api/python/messages/create
        # ---------------------------------------------------------
        #   self.client = our AsyncAnthropic SDK client
        #   .messages = the Messages API section of the SDK
        #   .create(...) = create/send a new Claude message request
        #   await = wait asynchronously for Anthropic to respond
        #
        # The object returned by Anthropic is stored in "message".
        #   request["messages"] is what we SEND to Claude.
        #   message is the response object we RECEIVE from Claude.
        message = await self.client.messages.create(
            **request   # **request = unpack the Python dictionary into named arguments
        )

        # This list comprehension, used to extract text parts from Claude's response:
        # [
        #     block.text
        #     for block in message.content
        #     if block.type == "text"
        # ]
        #
        # is equivalent to:
        #
        # text_parts = []
        # for block in message.content:
        #     if block.type == "text":
        #         text_parts.append(block.text)
        #
        # Why use a list comprehension instead of a for loop?
        # It is not required, but it works nicely here because the Claude SDK
        # gives us a collection of content block objects with predictable attributes
        # such as block.type and block.text.

        text_parts = [
            block.text
            for block in message.content # message.content contains Claude's response content blocks.
            if block.type == "text" # A response may contain different kinds of content blocks, so we only collect blocks whose type is "text".
        ]

        text = "\n".join(text_parts).strip() # Join all text blocks together using a newline.

        # Alongside text blocks, a response may contain "tool_use" blocks.
        # Each one is a request from Claude to run a tool and send the result back.
        tool_calls = tuple(
            ClaudeToolCall(
                id=block.id,
                name=block.name,
                arguments=dict(block.input), # block.input is already parsed JSON, never a raw string.
            )
            for block in message.content
            if block.type == "tool_use"
        )

        # Converts Anthropic's SDK response into our app's (simpler) ClaudeTextResult object.
        # This means routes and other services do not need to know the internal structure of the Anthropic response.
        return ClaudeTextResult(
            text=text, # Claude's generated text.
            model=message.model, # The model reported by Anthropic in the response.
            input_tokens=message.usage.input_tokens, # How many tokens Claude processed as input.
            output_tokens=message.usage.output_tokens, # How many tokens Claude generated as output.
            stop_reason=message.stop_reason, # "tool_use" when Claude is waiting for tool results.
            tool_calls=tool_calls, # Empty tuple when Claude did not ask for any tool.
        )

    async def generate_structured(
        self,
        user_message: str,
        *,
        schema: type[ModelT],
        max_tokens: int = 600,
        system: str | None = None,
    ) -> ClaudeStructuredResult[ModelT]:
        result = await self.generate_text(
            user_message=user_message,
            max_tokens=max_tokens,
            system=system,
        )

        payload = _extract_json_object(result.text)

        try:
            data = schema.model_validate(payload)
        except ValidationError as e:
            raise ClaudeResponseError(
                f"Claude returned JSON that does not match {schema.__name__}: {e}"
            ) from e

        return ClaudeStructuredResult(
            data=data,
            model=result.model,
            input_tokens=result.input_tokens,
            output_tokens=result.output_tokens,
        )
        
    # Turn one tool_use block from Claude into the tool_result block we must send back.
    # This is a helper for generate_with_tools() below, so it starts with an underscore.
    @staticmethod
    async def _run_tool(
        handlers: Mapping[str, ToolHandler],
        block,  # A "tool_use" content block from the Anthropic SDK.
    ) -> dict:
        handler = handlers.get(block.name)

        # Claude can only ask for tools we offered, but it may still hallucinate a name,
        # so an unknown tool is reported back as an error instead of crashing the loop.
        if handler is None:
            return {
                "type": "tool_result",
                "tool_use_id": block.id,
                "content": f"Unknown tool: {block.name}",
                "is_error": True,
            }

        try:
            # block.input is the arguments dict Claude filled in from our input_schema.
            output = await handler(dict(block.input))
        except Exception as e:
            # A failing tool is normal application life. Telling Claude about the failure
            # lets it apologise or try something else; raising here would abort the request.
            return {
                "type": "tool_result",
                "tool_use_id": block.id,
                "content": f"Tool {block.name} failed: {e}",
                "is_error": True,
            }

        return {
            "type": "tool_result",
            "tool_use_id": block.id,  # Must match the id of the tool_use block.
            "content": output,
        }

    # This method runs the full "agentic loop":
    #   1. Send the conversation to Claude together with the tool definitions.
    #   2. If Claude replies with tool_use blocks, run the matching handlers.
    #   3. Send the tool results back and ask Claude again.
    #   4. Repeat until Claude answers with normal text instead of a tool call.
    #
    # The Messages API is stateless, so we resend the whole conversation each round.
    async def generate_with_tools(
        self,
        user_message: str,
        *,
        # The tool schemas Claude may choose from.
        tools: list[dict],

        # Maps a tool name to the async function that actually performs it.
        # Every name in "tools" should have an entry here.
        handlers: Mapping[str, ToolHandler],

        max_tokens: int = 1000,
        system: str | None = None,

        # Safety net: without it, a confused model could loop forever and burn tokens.
        max_iterations: int = 5,
    ) -> ClaudeTextResult:

        # The growing conversation. It starts with the customer/user message.
        messages: list[dict] = [
            {
                "role": "user",
                "content": user_message,
            }
        ]

        # Every round costs tokens, so we add them up and report the total.
        input_tokens = 0
        output_tokens = 0
        model = self.model

        for _ in range(max_iterations):
            request = {
                "model": self.model,
                "max_tokens": max_tokens,
                "messages": messages,
                "tools": tools,
            }

            if system:
                request["system"] = system

            message = await self.client.messages.create(**request)

            model = message.model
            input_tokens += message.usage.input_tokens
            output_tokens += message.usage.output_tokens

            tool_uses = [
                block
                for block in message.content
                if block.type == "tool_use"
            ]

            # No tool requested means Claude is done: return its answer.
            if message.stop_reason != "tool_use" or not tool_uses:
                text_parts = [
                    block.text
                    for block in message.content
                    if block.type == "text"
                ]

                return ClaudeTextResult(
                    text="\n".join(text_parts).strip(),
                    model=model,
                    input_tokens=input_tokens,
                    output_tokens=output_tokens,
                    stop_reason=message.stop_reason,
                )

            # Claude's own turn goes back unchanged, tool_use blocks included.
            # Rewriting or dropping those blocks breaks the id matching below.
            messages.append(
                {
                    "role": "assistant",
                    "content": message.content,
                }
            )

            # Claude may request several tools at once, so run them concurrently.
            # asyncio.gather keeps the results in the same order as the requests.
            tool_results = await asyncio.gather(
                *(
                    self._run_tool(handlers, block)
                    for block in tool_uses
                )
            )

            # IMPORTANT: all tool results belong in ONE user message.
            # Splitting them across several messages teaches Claude to stop asking
            # for tools in parallel, which makes later requests slower.
            messages.append(
                {
                    "role": "user",
                    "content": list(tool_results),
                }
            )

        # Reaching this point means Claude kept asking for tools without ever answering.
        raise ClaudeResponseError(
            f"Claude did not produce a final answer within {max_iterations} tool rounds."
        )

    # This method streams Claude's answer piece by piece instead of waiting for the whole reply.
    # Because the body contains "yield", Python turns this into an async generator:
    # the caller uses "async for chunk in service.generate_text_stream(...)".
    # Typical use: FastAPI StreamingResponse, so the user sees text appear while Claude is still writing.
    async def generate_text_stream(
        self,
        user_message: str,          # The message/task we want Claude to process.
        *,
        max_tokens: int = 300,
        system: str | None = None,

        # Tools may be offered while streaming, but this method only yields TEXT.
        # If Claude decides to call a tool, nothing is yielded for it and nothing is executed.
        # Use generate_with_tools() when the tools must actually run.
        tools: list[dict] | None = None,
    ) -> AsyncIterator[str]:        # Each yielded value is a small piece ("delta") of Claude's text.

        # Same request shape as generate_text(); the streaming helper adds "stream": true for us.
        request = {
            "model": self.model,
            "max_tokens": max_tokens,
            "messages": [
                {
                    "role": "user",
                    "content": user_message,
                }
            ],
        }

        if system:
            request["system"] = system

        if tools:
            request["tools"] = tools

        # client.messages.stream(...) is the SDK's streaming helper.
        # "async with" keeps the HTTP connection open while we read, and closes it afterwards
        # even if the caller stops reading early or an error is raised.
        async with self.client.messages.stream(**request) as stream:

            # stream.text_stream yields only the text parts of the response,
            # so we do not have to inspect content blocks ourselves.
            async for chunk in stream.text_stream:
                yield chunk


    # This ClaudeService extension preserves raw Messages API content blocks so tool-use requests can be inspected safely.
    async def create_message(
        self,
        # Maintain the bounded conversation state sent back to Claude after each tool result.
        messages: list[dict[str, Any]],
        *,
        max_tokens: int = 600,
        system: str | None = None,
        tools: list[dict[str, Any]] | None = None,
    ) -> Any:
        # Tool-use responses may contain raw content blocks, not only text.
        request: dict[str, Any] = {
            "model": self.model,
            "max_tokens": max_tokens,
            "messages": messages,
        }

        if system:
            request["system"] = system

        # The application explicitly chooses which tools are offered to Claude.
        if tools:
            request["tools"] = tools

        return await self.client.messages.create(
            **request
        )


    async def close(self) -> None:
        await self.client.close()


def _extract_json_object(text: str) -> dict:
    """Parse the first JSON object in a Claude reply, tolerating code fences."""
    candidate = text.strip()

    if candidate.startswith("```"):
        candidate = candidate.split("```")[1]
        if candidate.lstrip().lower().startswith("json"):
            candidate = candidate.lstrip()[4:]
        candidate = candidate.strip()

    start = candidate.find("{")
    end = candidate.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ClaudeResponseError("Claude did not return a JSON object.")

    try:
        payload = json.loads(candidate[start : end + 1])
    except json.JSONDecodeError as e:
        raise ClaudeResponseError(f"Claude returned invalid JSON: {e}") from e

    if not isinstance(payload, dict):
        raise ClaudeResponseError("Claude returned JSON that is not an object.")

    return payload
